//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.20 at 02:22:21 PM CEST 
//


package de.fi.atm.types;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ATMOrderConfirmationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ATMOrderConfirmationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transactionid" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="confirmed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="charged" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="invoiced" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="showdate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="showtime" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *         &lt;element name="participant" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ticketno" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Reservation" type="{http://www.fi.de/atm/types}ConfirmationReservationType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ATMOrderConfirmationType", propOrder = {
    "transactionid",
    "confirmed",
    "charged",
    "invoiced",
    "showdate",
    "showtime",
    "participant",
    "productname",
    "ticketno",
    "reservation"
})
public class ATMOrderConfirmationType {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String transactionid;
    protected boolean confirmed;
    protected boolean charged;
    protected boolean invoiced;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar showdate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar showtime;
    @XmlElement(required = true)
    protected String participant;
    @XmlElement(required = true)
    protected String productname;
    @XmlElement(required = true)
    protected BigInteger ticketno;
    @XmlElement(name = "Reservation", required = true)
    protected ConfirmationReservationType reservation;

    /**
     * Gets the value of the transactionid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionid() {
        return transactionid;
    }

    /**
     * Sets the value of the transactionid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionid(String value) {
        this.transactionid = value;
    }

    /**
     * Gets the value of the confirmed property.
     * 
     */
    public boolean isConfirmed() {
        return confirmed;
    }

    /**
     * Sets the value of the confirmed property.
     * 
     */
    public void setConfirmed(boolean value) {
        this.confirmed = value;
    }

    /**
     * Gets the value of the charged property.
     * 
     */
    public boolean isCharged() {
        return charged;
    }

    /**
     * Sets the value of the charged property.
     * 
     */
    public void setCharged(boolean value) {
        this.charged = value;
    }

    /**
     * Gets the value of the invoiced property.
     * 
     */
    public boolean isInvoiced() {
        return invoiced;
    }

    /**
     * Sets the value of the invoiced property.
     * 
     */
    public void setInvoiced(boolean value) {
        this.invoiced = value;
    }

    /**
     * Gets the value of the showdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getShowdate() {
        return showdate;
    }

    /**
     * Sets the value of the showdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setShowdate(XMLGregorianCalendar value) {
        this.showdate = value;
    }

    /**
     * Gets the value of the showtime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getShowtime() {
        return showtime;
    }

    /**
     * Sets the value of the showtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setShowtime(XMLGregorianCalendar value) {
        this.showtime = value;
    }

    /**
     * Gets the value of the participant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParticipant() {
        return participant;
    }

    /**
     * Sets the value of the participant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParticipant(String value) {
        this.participant = value;
    }

    /**
     * Gets the value of the productname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductname() {
        return productname;
    }

    /**
     * Sets the value of the productname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductname(String value) {
        this.productname = value;
    }

    /**
     * Gets the value of the ticketno property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTicketno() {
        return ticketno;
    }

    /**
     * Sets the value of the ticketno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTicketno(BigInteger value) {
        this.ticketno = value;
    }

    /**
     * Gets the value of the reservation property.
     * 
     * @return
     *     possible object is
     *     {@link ConfirmationReservationType }
     *     
     */
    public ConfirmationReservationType getReservation() {
        return reservation;
    }

    /**
     * Sets the value of the reservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfirmationReservationType }
     *     
     */
    public void setReservation(ConfirmationReservationType value) {
        this.reservation = value;
    }

}
