
package de.fi.atm;

import javax.xml.ws.WebFault;
import de.fi.atm.types.ATMOrderErrorType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ATMOrderError", targetNamespace = "http://www.fi.de/atm/types")
public class ATMOrderError
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ATMOrderErrorType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ATMOrderError(String message, ATMOrderErrorType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ATMOrderError(String message, ATMOrderErrorType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: de.fi.atm.types.ATMOrderErrorType
     */
    public ATMOrderErrorType getFaultInfo() {
        return faultInfo;
    }

}
